default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DB_NAME") { "rails_with_prometheus" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "p@ssw0rd" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>

development:
  <<: *default

test:
  <<: *default
  database: rails_with_prometheus_test

production:
  <<: *default
  database: rails_with_prometheus_production
  username: rails_with_prometheus
  password: <%= ENV["RAILS_WITH_PROMETHEUS_DATABASE_PASSWORD"] %>
